### PR TITLE
Work on landingpage

### PR DESCRIPTION
**Pull request by Kolachi**
added text and reviews to landing page

### CODE REVIEW

**Comment by Kolachi** [comment]
Screen Shot 2020-08-20 at 4 33 58 PM

**Comment by Kolachi** [comment]
Screen Shot 2020-08-20 at 4 37 06 PM

**Review by leokrb — CHANGES_REQUESTED** [review]
Please put the new/green css in _card.scss into pages/_home.scss and resubmit :)

**Comment by leokrb** [comment]
Looking good, thanks!

**Pull request merged**
